# Generated by Django 3.0.7 on 2020-06-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Book',
        ),
    ]
