# Generated by Django 3.0.7 on 2020-06-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200616_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='au_detail',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
