# Generated by Django 3.0.7 on 2020-06-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200616_0350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
