# Generated by Django 3.0.7 on 2020-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='age',
            field=models.IntegerField(),
        ),
    ]
