# Generated by Django 3.0.7 on 2020-06-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20200616_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
