# Generated by Django 3.0.7 on 2020-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
