# Generated by Django 3.0.7 on 2020-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200616_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
